name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: Lint
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint
    - name: Test
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test
