name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yarn install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: yarn lint
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: lint
    - name: yarn test
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test
